-- Generated by scripts/generate-supabase-seed.ts from src/lib/data/seed.ts.
-- Do not hand-edit — re-run `npm run db:seed:gen` instead.

-- Seeded auth user (password sign-in, local test stack only).
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
) values (
  '00000000-0000-0000-0000-000000000000',
  '00000000-0000-0000-0000-000000000001',
  'authenticated',
  'authenticated',
  'test@local.dev',
  crypt('test-password-local', gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{}'::jsonb,
  now(),
  now(),
  '',
  '',
  '',
  ''
);

insert into auth.identities (
  id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000001',
  '{"sub":"00000000-0000-0000-0000-000000000001","email":"test@local.dev"}'::jsonb,
  'email',
  now(),
  now(),
  now()
);

insert into public.profiles (id, email, home_timezone) values
  ('00000000-0000-0000-0000-000000000001', 'test@local.dev', 'America/New_York');

insert into public.goals (id, user_id, name, date, target_seconds, payload) values
  ('goal-1', '00000000-0000-0000-0000-000000000001', 'Honolulu Marathon', '2026-12-13', 14400, '{"predictedSec":14170,"daysOut":165,"streak":12}'::jsonb);

insert into public.blocks (id, user_id, label, phase, week, total_weeks, periodization, payload) values
  ('block-1', '00000000-0000-0000-0000-000000000001', 'SUN · 12 MI', 'BUILD', 7, 16, '[{"phase":"base","mi":30},{"phase":"base","mi":33},{"phase":"base","mi":36},{"phase":"base","mi":38},{"phase":"build","mi":40},{"phase":"build","mi":43},{"phase":"build","mi":46},{"phase":"build","mi":44},{"phase":"peak","mi":48},{"phase":"peak","mi":50},{"phase":"peak","mi":52},{"phase":"peak","mi":49},{"phase":"taper","mi":44},{"phase":"taper","mi":38},{"phase":"taper","mi":32},{"phase":"taper","mi":26}]'::jsonb, '{"number":2,"weekMilesDone":32,"weekMilesTarget":41}'::jsonb);

insert into public.planned_sessions (id, user_id, date, title, type, detail, structure, status, provenance, payload) values
  ('mon-easy', '00000000-0000-0000-0000-000000000001', '2026-06-29', 'Easy run', 'easy', '4 mi · Zone 2', '[]'::jsonb, 'completed', 'original', '{"distanceMi":4,"zone":"Zone 2"}'::jsonb),
  ('tue-intervals', '00000000-0000-0000-0000-000000000001', '2026-06-30', 'Intervals', 'speed', '6 × 800m · Zone 4–5', '[]'::jsonb, 'completed', 'original', '{"distanceMi":5,"zone":"Zone 4–5"}'::jsonb),
  ('wed-400s', '00000000-0000-0000-0000-000000000001', '2026-07-01', 'Rolling 400s', 'speed', 'Intervals · 4.5 mi · ~45 min', '[{"kind":"warmup","label":"Warm up","zone":"Zone 2","pace":"Easy","duration":"10:00"},{"kind":"rep","label":"400m hard","zone":"Zone 5","pace":"5K pace","duration":"1:32","repeat":8},{"kind":"recovery","label":"200m float","zone":"easy","pace":"Recovery","duration":"1:05"},{"kind":"cooldown","label":"Cool down","zone":"Zone 1","pace":"Easy","duration":"10:00"}]'::jsonb, 'planned', 'original', '{"distanceMi":4.5,"paceTarget":"5K pace","zone":"Zone 4–5"}'::jsonb),
  ('thu-tempo', '00000000-0000-0000-0000-000000000001', '2026-07-02', 'Tempo', 'tempo', '6 mi · Zone 3–4', '[]'::jsonb, 'planned', 'original', '{"distanceMi":6,"zone":"Zone 3–4"}'::jsonb),
  ('fri-rest', '00000000-0000-0000-0000-000000000001', '2026-07-03', 'Rest', 'rest', 'Mobility', '[]'::jsonb, 'planned', 'original', '{}'::jsonb),
  ('sat-easy', '00000000-0000-0000-0000-000000000001', '2026-07-04', 'Easy run', 'easy', '5 mi · Zone 2', '[]'::jsonb, 'planned', 'original', '{"distanceMi":5,"zone":"Zone 2"}'::jsonb),
  ('sun-long', '00000000-0000-0000-0000-000000000001', '2026-07-05', 'Long run', 'long', '12 mi · Zone 2–3', '[]'::jsonb, 'planned', 'original', '{"distanceMi":12,"zone":"Zone 2–3"}'::jsonb);

insert into public.proposals (id, user_id, scope, session_id, status, payload) values
  ('proposal-1', '00000000-0000-0000-0000-000000000001', 'day', 'wed-400s', 'proposed', '{"headline":"Ease off today.","subhead":"Swap the 400s for an easy 4 miles.","rationale":"Readiness is down nine points and your Achilles flagged mild yesterday. A lighter day keeps the build on schedule without compounding load on the tendon — we''ll reassess in the morning.","badge":"HOLD","before":{"id":"wed-400s","date":"2026-07-01","type":"speed","title":"Rolling 400s","detail":"Intervals · 4.5 mi · ~45 min","distanceMi":4.5,"paceTarget":"5K pace","zone":"Zone 4–5","status":"planned","provenance":"original","structure":[{"kind":"warmup","label":"Warm up","zone":"Zone 2","pace":"Easy","duration":"10:00"},{"kind":"rep","label":"400m hard","zone":"Zone 5","pace":"5K pace","duration":"1:32","repeat":8},{"kind":"recovery","label":"200m float","zone":"easy","pace":"Recovery","duration":"1:05"},{"kind":"cooldown","label":"Cool down","zone":"Zone 1","pace":"Easy","duration":"10:00"}]},"after":{"id":"wed-400s","date":"2026-07-01","type":"easy","title":"Easy","detail":"4 mi · Zone 2 · 9:30/mi","distanceMi":4,"paceTarget":"9:30/mi","zone":"Zone 2","status":"planned","provenance":"accepted-proposal"},"drivers":[{"label":"HRV","value":"48","deltaPct":-12,"tone":"negative"},{"label":"SLEEP","value":"6:12","deltaText":"−1:32","tone":"negative"},{"label":"ACHILLES","value":"2/10 mild","tone":"warning"}],"reviewedAt":"6:41 AM"}'::jsonb),
  ('proposal-2', '00000000-0000-0000-0000-000000000001', 'week', 'sun-long', 'proposed', '{"headline":"Move long run to Saturday","subhead":"Rain forecast Sunday — shift the 12 miler.","rationale":"Heavy rain is forecast for Sunday morning. Moving the long run to Saturday keeps the key session intact without the weather risk.","badge":"ADJUST","before":{"id":"sun-long","date":"2026-07-05","type":"long","title":"Long run","detail":"12 mi · Zone 2–3","distanceMi":12,"zone":"Zone 2–3","status":"planned","provenance":"original"},"after":{"id":"sat-long-moved","date":"2026-07-04","type":"long","title":"Long run","detail":"12 mi · Zone 2–3 · moved from Sunday","distanceMi":12,"zone":"Zone 2–3","status":"planned","provenance":"original"},"drivers":[{"label":"WEATHER","value":"Rain · Sun","tone":"warning"},{"label":"LONG RUN","value":"12 mi","tone":"neutral"}],"reviewedAt":"6:41 AM"}'::jsonb),
  ('proposal-3', '00000000-0000-0000-0000-000000000001', 'workout', 'wed-400s', 'proposed', '{"headline":"Try 5 × 600m instead","subhead":"Same time in Zone 5, fewer hard accelerations.","rationale":"Same time in Zone 5 with fewer hard transitions — easier on turnover at nearly the same total time.","badge":"ADJUST","before":{"id":"wed-400s","date":"2026-07-01","type":"speed","title":"Rolling 400s","detail":"Intervals · 4.5 mi · ~45 min","distanceMi":4.5,"paceTarget":"5K pace","zone":"Zone 4–5","status":"planned","provenance":"original","structure":[{"kind":"warmup","label":"Warm up","zone":"Zone 2","pace":"Easy","duration":"10:00"},{"kind":"rep","label":"400m hard","zone":"Zone 5","pace":"5K pace","duration":"1:32","repeat":8},{"kind":"recovery","label":"200m float","zone":"easy","pace":"Recovery","duration":"1:05"},{"kind":"cooldown","label":"Cool down","zone":"Zone 1","pace":"Easy","duration":"10:00"}]},"after":{"id":"wed-400s","date":"2026-07-01","type":"speed","title":"Rolling 600s","detail":"5 × 600m · ~44 min","distanceMi":4.5,"paceTarget":"5K pace","zone":"Zone 4–5","status":"planned","provenance":"modified-proposal","structure":[{"kind":"warmup","label":"Warm up","zone":"Zone 2","pace":"Easy","duration":"10:00"},{"kind":"rep","label":"600m hard","zone":"Zone 5","pace":"5K pace","duration":"2:18","repeat":5},{"kind":"recovery","label":"200m float","zone":"easy","pace":"Recovery","duration":"1:05"},{"kind":"cooldown","label":"Cool down","zone":"Zone 1","pace":"Easy","duration":"10:00"}]},"drivers":[{"label":"REPS","value":"5×600m","tone":"neutral"},{"label":"TIME","value":"~44 min","tone":"neutral"},{"label":"ZONE 5","value":"same Z5 time","tone":"neutral"}],"reviewedAt":"6:41 AM","chatHeadline":"5 × 600m at 10K pace"}'::jsonb);

insert into public.pain_areas (id, user_id, name, severity, trend, payload) values
  ('achilles-l', '00000000-0000-0000-0000-000000000001', 'Achilles', 2, 'improving', '{"side":"Left","label":"mild","trendDays":7}'::jsonb),
  ('calf-r', '00000000-0000-0000-0000-000000000001', 'Calf', 1, 'steady', '{"side":"Right","label":"tight","trendDays":3}'::jsonb);

insert into public.recovery_snapshots (user_id, day, recovery_pct, hrv_ms, rhr, day_strain, sleep, source, payload) values
  ('00000000-0000-0000-0000-000000000001', '2026-06-25', 69, 55, 49, 1.05, '{"durationMin":430,"needMin":460,"efficiencyPct":91,"sleepScorePct":86,"deepMin":80,"remMin":95,"lightMin":255,"respRate":13.8}'::jsonb, 'whoop', '{"recoveryDelta":4,"hrvDeltaPct":2,"rhrDelta":-1,"loadLabel":"moderate"}'::jsonb),
  ('00000000-0000-0000-0000-000000000001', '2026-06-26', 59, 51, 50, 1.12, '{"durationMin":405,"needMin":460,"efficiencyPct":87,"sleepScorePct":80,"deepMin":70,"remMin":88,"lightMin":247,"respRate":14}'::jsonb, 'whoop', '{"recoveryDelta":-10,"hrvDeltaPct":-6,"rhrDelta":1,"loadLabel":"moderate"}'::jsonb),
  ('00000000-0000-0000-0000-000000000001', '2026-06-27', 63, 53, 50, 1.1, '{"durationMin":420,"needMin":460,"efficiencyPct":89,"sleepScorePct":82,"deepMin":72,"remMin":90,"lightMin":258,"respRate":13.9}'::jsonb, 'whoop', '{"recoveryDelta":4,"hrvDeltaPct":-2,"rhrDelta":0,"loadLabel":"moderate"}'::jsonb),
  ('00000000-0000-0000-0000-000000000001', '2026-06-28', 56, 50, 51, 1.18, '{"durationMin":390,"needMin":460,"efficiencyPct":85,"sleepScorePct":76,"deepMin":65,"remMin":82,"lightMin":243,"respRate":14.1}'::jsonb, 'whoop', '{"recoveryDelta":-7,"hrvDeltaPct":-8,"rhrDelta":1,"loadLabel":"elevated"}'::jsonb),
  ('00000000-0000-0000-0000-000000000001', '2026-06-29', 72, 56, 48, 0.95, '{"durationMin":445,"needMin":460,"efficiencyPct":93,"sleepScorePct":90,"deepMin":85,"remMin":100,"lightMin":260,"respRate":13.6}'::jsonb, 'whoop', '{"recoveryDelta":16,"hrvDeltaPct":4,"rhrDelta":-3,"loadLabel":"moderate"}'::jsonb),
  ('00000000-0000-0000-0000-000000000001', '2026-06-30', 67, 54, 49, 1.08, '{"durationMin":415,"needMin":460,"efficiencyPct":90,"sleepScorePct":83,"deepMin":74,"remMin":92,"lightMin":249,"respRate":13.9}'::jsonb, 'whoop', '{"recoveryDelta":-5,"hrvDeltaPct":-3,"rhrDelta":1,"loadLabel":"moderate"}'::jsonb),
  ('00000000-0000-0000-0000-000000000001', '2026-07-01', 62, 48, 52, 1.28, '{"durationMin":372,"needMin":464,"efficiencyPct":88,"sleepScorePct":78,"deepMin":67,"remMin":85,"lightMin":188,"respRate":14.2}'::jsonb, 'whoop', '{"recoveryDelta":-9,"hrvDeltaPct":-12,"rhrDelta":3,"loadLabel":"elevated"}'::jsonb);

insert into public.activities (user_id, sport, started_at, ended_at, distance_m, moving_sec, avg_pace_sec_per_mi, payload) values
  ('00000000-0000-0000-0000-000000000001', 'run', '2026-06-29T00:00:00Z', '2026-06-29T00:38:24.000Z'::timestamptz, 6437.376, 2304, 576, '{"id":"act-1","title":"Easy run · 4 mi","synced":true}'::jsonb);

insert into public.chat_messages (id, user_id, role, body, time_label, proposal_refs, seq, payload) values
  ('msg-0', '00000000-0000-0000-0000-000000000001', 'coach', 'Morning briefing: rain''s forecast for Sunday, so here''s one open proposal for this week before we get going.', '6:41', '["proposal-2"]'::jsonb, 0, '{}'::jsonb),
  ('msg-1', '00000000-0000-0000-0000-000000000001', 'coach', 'Recovery is at 62 — a bit below baseline. Rolling 400s still fit today, just keep the 200m floats truly easy.', '11:01', null, 1, '{}'::jsonb),
  ('msg-2', '00000000-0000-0000-0000-000000000001', 'user', 'My calves are tight from Monday. Should I still do the 400s?', null, null, 2, '{}'::jsonb),
  ('msg-3', '00000000-0000-0000-0000-000000000001', 'coach', 'Then let''s trade turnover for volume — same stimulus, gentler on the calves:', '11:02', '["proposal-3"]'::jsonb, 3, '{}'::jsonb);
